[burn-my-windows-profile]
fire-enable-effect=false
energize-b-enable-effect=false
energize-a-enable-effect=false
apparition-enable-effect=false
aura-glow-enable-effect=true
broken-glass-enable-effect=false
focus-enable-effect=false
glide-enable-effect=false
glitch-enable-effect=false
hexagon-enable-effect=false
incinerate-enable-effect=false
matrix-enable-effect=false
mushroom-enable-effect=false
paint-brush-enable-effect=false
paint-brush-animation-time=352
paint-brush-size=3
pixelate-enable-effect=false
pixel-wheel-enable-effect=false
portal-enable-effect=false
rgbwarp-enable-effect=false
snap-enable-effect=false
snap-animation-time=400
team-rocket-enable-effect=false
trex-enable-effect=false
tv-enable-effect=false
tv-glitch-enable-effect=false
wisps-enable-effect=false
doom-enable-effect=false
aura-glow-animation-time=544
aura-glow-start-hue=0.0
aura-glow-random-color=true
